### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by soyowendy** [soyowendy/CRUD-in-memory#1]
- [ ] Create Tests
- [ ] Use Database
- [ ] Try to use Design Patterns
- [ ] Create README

**Comment by soyowendy** [comment]
- [ ] Create Product Class
- [ ] Create Generic Data Access Object
- [ ] Use Annotation
